export default {
  login: 'shanto140319',
  id: 60308005,
  node_id: 'MDQ6VXNlcjYwMzA4MDA1',
  avatar_url: 'https://avatars.githubusercontent.com/u/60308005?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/shanto140319',
  html_url: 'https://github.com/shanto140319',
  followers_url: 'https://api.github.com/users/shanto140319/followers',
  following_url:
    'https://api.github.com/users/shanto140319/following{/other_user}',
  gists_url: 'https://api.github.com/users/shanto140319/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/shanto140319/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/shanto140319/subscriptions',
  organizations_url: 'https://api.github.com/users/shanto140319/orgs',
  repos_url: 'https://api.github.com/users/shanto140319/repos',
  events_url: 'https://api.github.com/users/shanto140319/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/shanto140319/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jahidul Haque Shanto',
  company: 'Own',
  blog: 'https://shanto-me.netlify.app/',
  location: 'Bangladesh',
  email: null,
  hireable: null,
  bio:
    'I recently completed my graduation in computer science and engineering from Daffodil International University. I am expert Html, CSS, JavaScript and React.',
  twitter_username: 'shanto_haque',
  public_repos: 26,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: '2020-01-26T04:08:19Z',
  updated_at: '2021-04-02T04:28:15Z',
}
